j2n7s300:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
    
  joint_group_position_controller:
    type: effort_controllers/JointGroupPositionController    
    joints:    
      - j2n7s300_joint_1              
      - j2n7s300_joint_2
      - j2n7s300_joint_3
      - j2n7s300_joint_4
      - j2n7s300_joint_5
      - j2n7s300_joint_6
      - j2n7s300_joint_7      
    j2n7s300_joint_1:
      pid: {p: 5000.0, i: 0.0, d: 5.0}
    j2n7s300_joint_2:
      pid: {p: 5000.0, i: 0.0, d: 5.0}    
    j2n7s300_joint_3:
      pid: {p: 5000.0, i: 0.0, d: 5.0}    
    j2n7s300_joint_4:
      pid: {p: 500.0, i: 0.0, d: 5.0}    
    j2n7s300_joint_5:
      pid: {p: 500.0, i: 0.0, d: 5.0}    
    j2n7s300_joint_6:
      pid: {p: 500.0, i: 0.0, d: 5.0}    
    j2n7s300_joint_7:
      pid: {p: 500.0, i: 0.0, d: 5.0}

  effort_joint_torque_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
      - j2n7s300_joint_1              
      - j2n7s300_joint_2
      - j2n7s300_joint_3
      - j2n7s300_joint_4
      - j2n7s300_joint_5
      - j2n7s300_joint_6
      - j2n7s300_joint_7 